name: Github AWS OIDC Integration

on: [pull_request]

jobs:
    configure_aws:
        if: false
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        name: A test of the github aws oidc integration
        steps:
          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
                audience: sts.amazonaws.com
                aws-region: us-east-1
                role-to-assume: arn:aws:iam::183631350996:role/IaC-ReadOnly
