name: terraform-apply

on:
  push:
    branches:
      - main
    paths:
      - "terraform/aws/**"
      - ".github/workflows/tf-plan.yaml"
      - ".github/workflows/tf-apply.yaml"

concurrency:
  group: terraform

jobs:
  terraform-apply:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    uses: yashrajdighe/github-actions-reusable-workflows/.github/workflows/tf-apply.yaml@main
    with:
      working-dir: "terraform/aws"
      enable-oidc-debugger: true
