name: terraform plan

on:
  pull_request:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls
  terraform-plan:
    needs: checkout
    uses: yashrajdighe/github-actions-reusable-workflows/.github/workflows/tf-plan.yaml@CLOUD-2-add-tf-plan-reusable-action
