name: terraform-plan

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    uses: yashrajdighe/github-actions-reusable-workflows/.github/workflows/tf-plan.yaml@CLOUD-2-add-tf-plan-reusable-action
    with:
      working-dir: "terraform/aws"
